version: "3"
services:
  records-ms:
    image: genealogix-records-api
    container_name: genealogix_records_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    depends_on:
      - mongodb
    links:
      - mongodb
    stdin_open: true
    tty: true
    volumes:
      - ~/.aws/credentials:/home/app/.aws/credentials:ro
  
  mongodb:
    image: mongo
    ports: 
      - "27016:27017"
    volumes:
      - data:/data/db

volumes:
  data: